import About from "../images/about.png";

export const data = [
  {
    picture: About,
    button: "https://example.com/vote1",
    name: "Jane",
    number: "08078598754",
    rank: 0,
    voteCount: 0,
  },
  {
    picture: About,
    button: "https://example.com/vote1",
    name: "Beatrice",
    number: "08078598754",
    rank: 0,
    voteCount: 0,
  },
  {
    picture: About,
    button: "https://example.com/vote1",
    name: "Chinonye",
    number: "08078598754",
    rank: 0,
    voteCount: 0,
  },
  {
    picture: About,
    button: "https://example.com/vote1",
    name: "Queen",
    number: "08078598754",
    rank: 0,
    voteCount: 0,
  },
  {
    picture: About,
    button: "https://example.com/vote1",
    name: "Jennifer",
    number: "08078598754",
    rank: 0,
    voteCount: 0,
  },
  {
    picture: About,
    button: "https://example.com/vote1",
    name: "Chioma",
    number: "08078598754",
    rank: 0,
    voteCount: 0,
  },
  {
    picture: About,
    button: "https://example.com/vote1",
    name: "Joy",
    number: "08078598754",
    rank: 0,
    voteCount: 0,
  },
  {
    picture: About,
    button: "https://example.com/vote1",
    name: "Peace",
    number: "08078598754",
    rank: 0,
    voteCount: 0,
  },
  {
    picture: About,
    button: "https://example.com/vote1",
    name: "princess",
    number: "08078598754",
    rank: 0,
    voteCount: 0,
  },
];
